namespace Jibo.Cloud.Api.Hosting.Config;

internal enum AdminConfigValueType
{
    String,
    Boolean,
    Integer,
    Number
}

internal sealed record AdminConfigDescriptor(
    string Key,
    string Section,
    string Label,
    string Description,
    AdminConfigValueType ValueType,
    string? DefaultValue,
    bool IsSecret,
    bool RequiresRestart,
    string? Placeholder = null);

/// <summary>
/// Single source of truth for admin-editable OpenJibo configuration keys.
/// </summary>
internal static class AdminConfigDescriptorRegistry
{
    internal static IReadOnlyList<AdminConfigDescriptor> All { get; } =
    [
        new("OpenJibo:Deployment:Mode", "Hosting", "Deployment mode",
            "managed, self-hosted-proxied, self-hosted-isolated, or self-hosted-hybrid.",
            AdminConfigValueType.String, "managed", false, true,
            "self-hosted-proxied"),
        new("OpenJibo:Security:Mode", "Hosting", "Security mode",
            "When true, requires TLS even for isolated self-hosting.",
            AdminConfigValueType.Boolean, null, false, true),
        new("OpenJibo:CanonicalApiHostname", "Hosting", "Canonical API hostname",
            "Primary robot-facing hostname advertised by this cloud.",
            AdminConfigValueType.String, "api.5x1.com", false, true),
        new("OpenJibo:CanonicalApiBaseUrl", "Hosting", "Canonical API base URL",
            "Optional absolute https:// base URL for protocol responses.",
            AdminConfigValueType.String, null, false, true, "https://api.5x1.com"),
        new("OpenJibo:SelfHosted:AllowTokenlessSingleRobotHub", "Hosting", "Allow tokenless hub",
            "Only for self-hosted-isolated private LAN deployments.",
            AdminConfigValueType.Boolean, "false", false, true),

        new("OpenJibo:State:Backend", "Persistence", "State backend",
            "Sqlite, File, PostgreSql, AzureBlob, or AzureSql.",
            AdminConfigValueType.String, "Sqlite", false, true),
        new("OpenJibo:State:PersistencePath", "Persistence", "State persistence path",
            "JSON locator path; Sqlite derives a .db beside it.",
            AdminConfigValueType.String, "App_Data/cloud-state.json", false, true),
        new("OpenJibo:State:ConnectionString", "Persistence", "State connection string",
            "Optional explicit connection string for Sql/Blob backends.",
            AdminConfigValueType.String, null, true, true),
        new("OpenJibo:PersonalMemory:Backend", "Persistence", "Personal memory backend",
            "Sqlite, File, PostgreSql, AzureBlob, or AzureSql.",
            AdminConfigValueType.String, "Sqlite", false, true),
        new("OpenJibo:PersonalMemory:PersistencePath", "Persistence", "Personal memory path",
            "JSON locator path; Sqlite derives a .db beside it.",
            AdminConfigValueType.String, "App_Data/personal-memory.json", false, true),
        new("OpenJibo:PersonalMemory:ConnectionString", "Persistence", "Personal memory connection string",
            "Optional explicit connection string.",
            AdminConfigValueType.String, null, true, true),

        new("OpenJibo:Stt:EnableLocalWhisperCpp", "Speech", "Enable local whisper.cpp CLI",
            "Batch STT via whisper-cli subprocess.",
            AdminConfigValueType.Boolean, "false", false, true),
        new("OpenJibo:Stt:EnableWhisperServer", "Speech", "Enable whisper-server",
            "Batch STT via warm local whisper-server HTTP.",
            AdminConfigValueType.Boolean, "false", false, true),
        new("OpenJibo:Stt:EnableStreamingSherpa", "Speech", "Enable streaming Sherpa STT",
            "Incremental Zipformer recognition while the user speaks.",
            AdminConfigValueType.Boolean, "false", false, true),
        new("OpenJibo:Stt:EnableAzureSpeech", "Speech", "Enable Azure Speech",
            "Cloud batch STT via Azure Cognitive Services.",
            AdminConfigValueType.Boolean, "false", false, true),
        new("OpenJibo:Stt:AutoStartWhisperServer", "Speech", "Auto-start whisper-server",
            "Start a loopback whisper-server if one is not already listening.",
            AdminConfigValueType.Boolean, "true", false, true),
        new("OpenJibo:Stt:FfmpegPath", "Speech", "ffmpeg path",
            "Path to ffmpeg for Opus→WAV conversion.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:WhisperCliPath", "Speech", "whisper-cli path",
            "Path to whisper.cpp whisper-cli binary.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:WhisperModelPath", "Speech", "Whisper model path",
            "Path to ggml*.bin model file.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:WhisperServerUrl", "Speech", "Whisper server URL",
            "HTTP base URL for whisper-server.",
            AdminConfigValueType.String, "http://127.0.0.1:8090", false, true),
        new("OpenJibo:Stt:WhisperServerBinPath", "Speech", "whisper-server binary",
            "Optional path to whisper-server binary.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:SherpaModelDirectory", "Speech", "Sherpa model directory",
            "Directory containing Zipformer encoder/decoder/joiner ONNX files.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:AzureSpeechRegion", "Speech", "Azure Speech region",
            "Azure region for Speech services.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:AzureSpeechSubscriptionKey", "Speech", "Azure Speech subscription key",
            "Azure Speech API key.",
            AdminConfigValueType.String, null, true, true),
        new("OpenJibo:Stt:WhisperLanguage", "Speech", "Whisper language",
            "Language code passed to whisper.",
            AdminConfigValueType.String, "en", false, true),
        new("OpenJibo:Stt:WhisperAudioContext", "Speech", "Whisper audio context",
            "whisper --audio-ctx value.",
            AdminConfigValueType.Integer, "512", false, true),
        new("OpenJibo:Stt:WhisperThreads", "Speech", "Whisper threads",
            "0 means Environment.ProcessorCount.",
            AdminConfigValueType.Integer, "0", false, true),
        new("OpenJibo:Stt:WhisperBeamSize", "Speech", "Whisper beam size",
            "whisper -bs value.",
            AdminConfigValueType.Integer, "1", false, true),
        new("OpenJibo:Stt:TempDirectory", "Speech", "STT temp directory",
            "Scratch directory for Ogg/WAV intermediates.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Stt:CleanupTempFiles", "Speech", "Cleanup STT temp files",
            "Delete intermediate audio after transcription.",
            AdminConfigValueType.Boolean, "false", false, true),

        new("OpenJibo:Listen:EnableModelEndpointing", "Speech", "Enable model endpointing",
            "Use Sherpa IsEndpoint + utterance completeness instead of the fixed 350ms silence timer. Requires streaming Sherpa.",
            AdminConfigValueType.Boolean, "false", false, true),
        new("OpenJibo:Listen:Rule2MinTrailingSilenceSeconds", "Speech", "Endpoint trailing silence (s)",
            "Sherpa Rule2 trailing-silence threshold in seconds.",
            AdminConfigValueType.Number, "0.6", false, true),
        new("OpenJibo:Listen:Rule1MinTrailingSilenceSeconds", "Speech", "Endpoint Rule1 silence (s)",
            "Sherpa Rule1 trailing-silence threshold in seconds.",
            AdminConfigValueType.Number, "0.4", false, true),
        new("OpenJibo:Listen:DefaultMaxUtteranceSeconds", "Speech", "Default max utterance (s)",
            "Fallback Rule3 max utterance when the robot omits maxSpeechTimeout.",
            AdminConfigValueType.Number, "20", false, true),

        new("OpenJibo:Logging:MinimumLevel", "Logging", "Minimum log level",
            "Verbose, Debug, Information, Warning, Error, or Fatal.",
            AdminConfigValueType.String, "Information", false, true),
        new("OpenJibo:Logging:DirectoryPath", "Logging", "Log directory",
            "Serilog rolling file directory.",
            AdminConfigValueType.String, "captures/logs", false, true),
        new("OpenJibo:Logging:FileName", "Logging", "Log file name pattern",
            "Serilog rolling file name prefix.",
            AdminConfigValueType.String, "openjibo-.log", false, true),
        new("OpenJibo:Logging:ResetOnStartup", "Logging", "Reset captures on startup",
            "Deletes capture/telemetry directories on boot (not log files).",
            AdminConfigValueType.Boolean, "false", false, true),
        new("OpenJibo:Telemetry:Enabled", "Logging", "WebSocket telemetry enabled",
            "Write websocket capture NDJSON.",
            AdminConfigValueType.Boolean, "true", false, true),
        new("OpenJibo:Telemetry:ExportFixtures", "Logging", "Export websocket fixtures",
            "Write .flow.json fixtures on socket close.",
            AdminConfigValueType.Boolean, "true", false, true),
        new("OpenJibo:Telemetry:RetentionDays", "Logging", "WebSocket capture retention days",
            "0 disables age pruning.",
            AdminConfigValueType.Integer, "7", false, true),
        new("OpenJibo:ProtocolTelemetry:Enabled", "Logging", "HTTP telemetry enabled",
            "Write protocol capture NDJSON.",
            AdminConfigValueType.Boolean, "true", false, true),
        new("OpenJibo:ProtocolTelemetry:RetentionDays", "Logging", "HTTP capture retention days",
            "0 disables age pruning.",
            AdminConfigValueType.Integer, "7", false, true),
        new("OpenJibo:TurnTelemetry:Enabled", "Logging", "Turn telemetry enabled",
            "Write turn diagnostic NDJSON.",
            AdminConfigValueType.Boolean, "true", false, true),
        new("OpenJibo:TurnTelemetry:RetentionDays", "Logging", "Turn capture retention days",
            "0 disables age pruning.",
            AdminConfigValueType.Integer, "7", false, true),

        new("OpenJibo:Weather:OpenWeather:ApiKey", "Integrations", "OpenWeather API key",
            "Used for weather skill answers.",
            AdminConfigValueType.String, null, true, true),
        new("OpenJibo:Weather:OpenWeather:DefaultLocation", "Integrations", "Default weather location",
            "Fallback city when the robot does not specify one.",
            AdminConfigValueType.String, "Boston,US", false, true),
        new("OpenJibo:News:NewsApi:ApiKey", "Integrations", "NewsAPI key",
            "Used for news skill answers.",
            AdminConfigValueType.String, null, true, true),
        new("OpenJibo:Search:Primary", "Integrations", "Primary search backend",
            "none, Wolfram!appId, ChatGPT!apiKey!model, or Ollama!url!model.",
            AdminConfigValueType.String, "none", false, true),
        new("OpenJibo:Search:Fallback", "Integrations", "Fallback search backend",
            "Optional fallback backend string.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:Holiday:CountryCode", "Integrations", "Holiday country code",
            "ISO country code for holiday calendar.",
            AdminConfigValueType.String, "US", false, true),

        new("OpenJibo:Portal:StatusPassword", "Portal", "Admin status password",
            "Password for /portal/status and admin tools.",
            AdminConfigValueType.String, null, true, true),
        new("OpenJibo:Portal:SessionSigningKey", "Portal", "Portal session signing key",
            "HMAC secret for portal session tokens.",
            AdminConfigValueType.String, null, true, true),

        new("OpenJibo:Robot:RobotId", "Robot", "Robot ID override",
            "Optional single-robot device override.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:OwnerFirstName", "Robot", "Owner first name",
            "Seeded into cloud state for new loops.",
            AdminConfigValueType.String, null, false, true),
        new("OpenJibo:OwnerLastName", "Robot", "Owner last name",
            "Seeded into cloud state for new loops.",
            AdminConfigValueType.String, null, false, true)
    ];

    internal static AdminConfigDescriptor? Find(string key) =>
        All.FirstOrDefault(descriptor =>
            string.Equals(descriptor.Key, key, StringComparison.OrdinalIgnoreCase));
}
